[package]
name = "ptx_runtime_compile"
version = "0.1.0"
edition = "2024"

[dependencies]
maize_core = { path = "./crates/maize_core" }
maize_types = { path = "./crates/maize_types" }
maize_pipe = { path = "./crates/maize_pipe" }
# maize_tile = { path = "./crates/maize_tile" }
maize_py = { path = "./crates/maize_py" }
maize_cob = { path = "./crates/maize_cob" }
# old_maize_core = { path = "./crates/old_maize_core" }

[profile.release]
debug = true
