class DType:
    def to_str(self) -> str: ...
    @classmethod
    def try_from_str(cls, val: str) -> DType | None: ...
    @classmethod
    def from_str(cls, val: str) -> DType: ...

class Shape:
    def __init__(self, *values: Shape | int): ...

class Stride:
    def __init__(self, *values: Shape | int): ...

class Tile:
    def __init__(self, shape: Shape, dtype: DType): ...

def hello(name: str) -> str: ...
